### ISSUE TITLE
Not being able to overwrite assets with their compressed version

### ISSUE THREAD

**Issue by szanata** [webpack-contrib/compression-webpack-plugin#187]
- Operating System: Alpine
- Node Version: 14.9.0
- NPM Version: 6.14.8
- webpack Version: 4.41.1
- compression-webpack-plugin Version: 5.0.1

### Expected Behavior

Up until version 4.x, I could config `filename` to be the same name as the webpack output files (eg. `[path][query]`). This would overwrite the output files in the dist folder with a compressed version.

### Actual Behavior

After migrating to the latest version 5.0.1, the files are not being overwritten anymore. I'm receiving a warning from Webpack when trying to save compressed files with the same name as the output files:

<img width="790" alt="Screen Shot 2020-08-31 at 19 25 44" src="https://user-images.githubusercontent.com/221676/91774751-eadf3900-ebbf-11ea-8634-05a3ffc39774.png">

Message: `WARNING in Conflict: Multiple assets emit different content to the same filename XXX.X`

If I rename the compression filename to anything else, like adding the `.gz` it works.

### Code

```js
// webpack.production.js
...
  plugins: [
    new CompressionPlugin( {
      test: /\.(js|css|html|svg|LICENSE)$/,
      filename: '[path][query]',
      algorithm: 'brotliCompress',
      compressionOptions: {
        level: 11
      },
      threshold: 0,
      minRatio: 0.8
    } ),
  ]
...
```

and

```js
// webpack.common.js

const webpack = require( 'webpack' );
const distPath = resolve( __dirname, 'dist' );
const srcPath = resolve( __dirname, 'src' );

module.exports = {
  context: srcPath,
  entry: {
    main: './app.js'
  },
  output: {
    path: distPath,
    filename: 'app.[chunkhash].js'
  },
};
```

### How Do We Reproduce?

Just set the plugin to use `filename: [path][query]` and execute the webpack bundling.

**Comment by evilebottnawi** [comment]
It is expected, you can't have assets with same names twice, they will overrides themselves, just like you cannot have two different files in the file system with the same path, change it to `filename: '[path].br',`

**Comment by szanata** [comment]
I see. Thanks for the reply.

**Comment by seebigs** [comment]
> It is expected, you can't have assets with same names twice, they will overrides themselves, just like you cannot have two different files in the file system with the same path, change it to `filename: '[path].br',`

@evilebottnawi Could I ask you to please revaluate that choice? It would be great to allow this as an opt-in behavior.

Some folks (myself included) will face a use case where we've configured webpack to output some files that we intend to serve over a cdn (dist/partner1.js, dist/partner2.js, dist/partner3.js, and so on). While developing I'd like to output those files minified but uncompressed -- so that I can inspect them and debug them without running through a utility to unzip them, without needing to setup my local test server to serve zipped resources, and without needing to wait for compression to finish on each rebuild. However, when in CI mode I'd like to compress them so that they're ready to upload to our cdn (which does not do its own compression because CloudFront doesn't handle etags properly).

Previously I would just apply the compression plugin only when in CI mode and overwrite those files with a compressed version of themselves, but now that throws a halting error. Do you have a proposed solution for this?

Seems like I shouldn't need to conditionally change my output file names to something different (like dist/partner1.uncompressed) only when in CI mode, just so that the compression plugin can then claim the real file names and then delete the uncompressed ones. This would change the filename matching rules for any other plugins as well, and could cause other issues that don't appear until after we've merged code.

**Comment by defualt** [comment]
Overwriting was happening in v4.  I upgraded and it broke my deployment.  Now I need to implement a post build script to do this.

**Comment by evilebottnawi** [comment]
@seebigs We can implement `force` option to override existing assets, maybe you can provide more information

**Comment by defualt** [comment]
I'm uploading gzipped JS bundles to S3 with gzip content encoding headers, and those files are served from S3 urls.

**Comment by szanata** [comment]
@defualt That was my use case as well. What I do now is to remove the `.br` extension from the filename when uploading to S3. That being said @evilebottnawi, it would be very nice to have an `force` or `overwrite` option, just to have more flexibility on the output.

**Comment by evilebottnawi** [comment]
@szanata Can you open a new issue and describe it, it will be very easy to implement

**Comment by szanata** [comment]
@evilebottnawi sure, thanks!
