### ISSUE TITLE
when i was compressed files,there were only one gz file left

### ISSUE THREAD

**Issue by Sshhcc** [webpack-contrib/compression-webpack-plugin#243]
code:
"use strict";
const CompressionWebpackPlugin = require("compression-webpack-plugin");
const productionGzipExtensions = ["js", "css"];
module.exports = {
    lintOnSave: process.env.NODE_ENV !== 'production',
    productionSourceMap: false,
    configureWebpack: {
        plugins: [
            new CompressionWebpackPlugin({
              filename: "[path].gz[query]",
              algorithm: "gzip",
              test: new RegExp("\\.(" + productionGzipExtensions.join("|") + ")$"),
              threshold: 10240,
              minRatio: 0.8,
              deleteOriginalAssets: false
            })
        ]
    },
}

![image](https://user-images.githubusercontent.com/17444344/106248370-d9bc5600-624b-11eb-877f-d48b1c4cfa27.png)

**Comment by Sshhcc** [comment]
is this correct?

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

Please respect time of other developers. Your issue is not readable.

Try `filename: "[path][name].gz[query]"`
