### ISSUE TITLE
How to use deleteOriginalAssets is true ？

### ISSUE THREAD

**Issue by zhenghaiyang** [webpack-contrib/compression-webpack-plugin#356]
Hey there! If you need support, help, or advice then this is not the place to ask.
Please visit [Discussions](https://github.com/webpack/webpack/discussions), [StackOverflow](https://stackoverflow.com/questions/tagged/webpack)
or [the Webpack Gitter](https://gitter.im/webpack/webpack) instead.

I would like to know in which situations the deleteOriginalAssets parameter is used to delete original files after compression. I have tried using Vue with deleteOriginalAssets set to true, which results in only .gz files being produced after building. However, when deployed on Nginx, the page cannot be opened.

**Comment by alexander-akait** [comment]
Sorry, I can't help here, because I don't know your nginx version and nginx configurations, there is the same question https://serverfault.com/questions/571733/nginx-gzip-static-why-are-the-non-compressed-files-required, just check your configuration, check your versions, do test with `curl`.

feel free to feedback

**Comment by zhenghaiyang** [comment]
thanks。Let me try

**Comment by zhenghaiyang** [comment]
> Sorry, I can't help here, because I don't know your nginx version and nginx configurations, there is the same question https://serverfault.com/questions/571733/nginx-gzip-static-why-are-the-non-compressed-files-required, just check your configuration, check your versions, do test with `curl`.
> 
> feel free to feedback

thanks。Let me try
