### ISSUE TITLE
Brotli support

### ISSUE THREAD

**Issue by gauravdewan007** [webpack-contrib/compression-webpack-plugin#92]
Goal of this plugin is to Prepare compressed versions of assets to serve them with Content-Encoding. Currently it supports gzip but it can be expanded to support brotli compression (and maybe combine zopfli - which is there elsewhere in this git org).
Brotli is supported by all modern browsers now. This plugin could provide defaul option to use brotli with fallback to gzip.

**Comment by evilebottnawi** [comment]
@gauravdewan007 PR welcome :+1:

**Comment by robcresswell** [comment]
There is already a [brotli plugin](https://github.com/mynameiswhm/brotli-webpack-plugin) - perhaps we could use the code from there?

In terms of format I'd suggest defaulting to gzip and adding a config flag to upgrade to brotli, for compatibility reasons. Otherwise people using the compression plugin with older browsers would see their current workflow break.

**Comment by robcresswell** [comment]
This PR from 2016 is also relevant: https://github.com/webpack-contrib/compression-webpack-plugin/pull/31

**Comment by evilebottnawi** [comment]
@robcresswell i think it is out of scope this plugin, better create other plugin for this purpose.
@michael-ciniawsky thank do you think?

**Comment by robcresswell** [comment]
It sounds a lot like the other repo is basically a clone of this one with a different compression lib, judging from the config and README.

**Comment by evilebottnawi** [comment]
@robcresswell we can add option `package` (need better name) and use here https://github.com/webpack-contrib/compression-webpack-plugin/blob/master/src/index.js#L44 to load from need package, let's wait what says @michael-ciniawsky

**Comment by mynameiswhm** [comment]
> i think it is out of scope this plugin, better create other plugin for this purpose.

@evilebottnawi oh whait, there _is_ [another plugin for this purpose](https://github.com/mynameiswhm/brotli-webpack-plugin) already which is being discussed in this thread :)

@robcresswell the reason for not stuffing every single compression algorithm into one plugin is to not download/compile a lot of unnecessary compression dependencies if you only need gzip.
The only real problem that plugin for gzip compression is historically called `compression-webpack-plugin`, not `gzip-webpack-plugin`, which may be misleading for newcomers.

**Comment by robcresswell** [comment]
Yeah, that makes sense I suppose. Just seems a shame to maintain two very similar plugins separately.

**Comment by michael-ciniawsky** [comment]
Since most alternative compression algorithms require a native addon, `compression-webpack-plugin` will only support what is being provided by `node` (GZIP) itself to avoid possible cross platform issues. Therefore support for alternative algorithms in `compression-webpack-plugin` is not planned atm.
